namespace FhirSide.Core.Models;

/// <summary>
/// Represents the status of a bulk export job.
/// </summary>
public enum BulkExportStatus
{
    /// <summary>Export job is in progress.</summary>
    InProgress,
    /// <summary>Export job completed successfully.</summary>
    Completed,
    /// <summary>Export job failed.</summary>
    Failed
}

/// <summary>
/// Represents a bulk export job for FHIR Bulk Data Access.
/// </summary>
public class BulkExportJob
{
    /// <summary>
    /// Unique identifier for the export job.
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Current status of the export job.
    /// </summary>
    public BulkExportStatus Status { get; set; } = BulkExportStatus.InProgress;

    /// <summary>
    /// Type of export: "system" for /$export or "patient" for /Patient/$export.
    /// </summary>
    public string ExportType { get; set; } = string.Empty;

    /// <summary>
    /// Timestamp when the export was requested.
    /// </summary>
    public DateTime RequestedAt { get; set; }

    /// <summary>
    /// Timestamp when the export completed or failed.
    /// </summary>
    public DateTime? CompletedAt { get; set; }

    /// <summary>
    /// Error message if the export failed.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Base URL used for constructing download URLs.
    /// </summary>
    public string BaseUrl { get; set; } = string.Empty;

    /// <summary>
    /// List of output files generated by the export.
    /// </summary>
    public List<BulkExportOutput> Output { get; set; } = new();
}

/// <summary>
/// Represents an output file from a bulk export job.
/// </summary>
public class BulkExportOutput
{
    /// <summary>
    /// FHIR resource type contained in this file.
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// URL to download the NDJSON file.
    /// </summary>
    public string Url { get; set; } = string.Empty;

    /// <summary>
    /// Number of resources in the file.
    /// </summary>
    public int Count { get; set; }

    /// <summary>
    /// File name for the export file.
    /// </summary>
    public string FileName { get; set; } = string.Empty;
}
